$("#compass").roundSlider({
    sliderType: "min-range",
    radius: 18,
    showTooltip: false,
    width: 0,
    value: 0,
    handleSize: 0,
    handleShape: "square",
    startAngle: 90,
    min: 0,
    max: 360,
    beforeCreate: "traceEvent",
    create: "traceEvent",
    start: "traceEvent",
    stop: "traceEvent",
    change: "traceEvent",
    drag: "traceEvent",
    cursor: 'pointer',
});
